name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu

            if [ ! -d "Hire-Heaven-Job-Portal" ]; then
              git clone https://github.com/devesh712005/Hire-Heaven-Job-Portal.git
            fi

            cd Hire-Heaven-Job-Portal

            git fetch origin
            git reset --hard origin/main

            docker system prune -a -f || true
            docker builder prune -a -f || true

            docker-compose down --remove-orphans || true

            docker rm -f $(docker ps -aq) || true

            docker-compose build --no-cache

            docker-compose up -d

            docker image prune -f

            docker ps
