export const checkToxic = (text) => {
  const words = [
    "bitch",
    "asshole",
    "fuck",
    "fucker",
    "fucking",
    "motherfucker",
    "mf",
    "bastard",
    "son of a bitch",
    "slut",
    "whore",
    "dick",
    "dickhead",
    "cock",
    "pussy",
    "prick",
    "twat",
    "cunt",
    "jackass",
    "dumbass",
    "shit",
    "bullshit",
    "shithead",
    "dipshit",
    "retard",
    "retarded",
    "moron",
    "idiot",
    "stupid",
    "dumb",
    "loser",
    "trash",
    "garbage",
    "scumbag",
    "jerk",
    "jerkoff",
    "tool",
    "piece of shit",
    "pos",
    "screw you",
    "screw off",
    "shut up",
    "go to hell",
    "kill yourself",
    "kys",
    "die",
    "bastard",
    "hell",
    "drop dead",
    "pathetic",
    "ugly",
    "disgusting",
    "freak",
    "weirdo",
    "psycho",
    "lunatic",
    "madarchod",
    "bhosdike",
    "chutiya",
    "gandu",
    "harami",
    "kutte",
    "kamina",
    "lund",
    "lawda",
    "bc",
    "mc",
    "behenchod",
    "maachod",
    "rand",
    "suck",
    "bsdk",
    "mc",
    "madarchod",
    "aulaad",
    "suar",
    "pig",
    "randi",
    "saala",
    "ullu",
    "nalayak",
    "bakwas",
    "pagal",
    "bewakoof",
    "chakka",
    "chod",
    "chodna",
    "gand",
    "gaand",
    "jhant",
    "jhantu",
    "lodu",
    "tatti",
    "gaandfat",
    "lavde",
    "lawde",
    "gaandmar",
    "bkl",
    "mkc",
    "randiya",
    "haramzada",
    "gandmasti",
    "kutti",
    "kuttiya",
    "saali",
    "tattihead",
    "shitface",
    "arse",
    "arsehole",
    "bloody idiot",
    "bloody fool",
    "stfu",
    "gtfo",
    "wtf",
  ];

  return words.some((w) => new RegExp(`(^|\\s)${w}(\\s|$)`, "i").test(text));
};

export const checkSpam = (text) => {
  const patterns = [
    /\b(free money|earn cash|get rich)\b/i,
    /\b(click this link|urgent action)\b/i,
    /\b(win.*prize|claim.*reward)\b/i,
  ];

  return patterns.some((p) => p.test(text));
};

export const extractURL = (text) => {
  const match = text.match(/http[s]?:\/\/\S+/);
  return match ? match[0] : null;
};
